challenges/urls.py
from django.conf.urls import patterns, url

from challenges import views

# routes to the correct view handler
urlpatterns = patterns('',
	url(r'^$', views.challenge_index, name='index'),
	url(r'^challenge_update/$', views.challenge_update, name='challenge_update'),
	url(r'^challenge_complete/$', views.challenge_complete, name='challenge_complete'),
	url(r'^challenge_reward/$', views.challenge_reward, name='challenge_reward'),

)

clsd_app/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'clsd_app.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^', include('dashboard.urls', namespace="dashboard")),
    url(r'^dashboard/', include('dashboard.urls', namespace="dashboard")),
    url(r'^challenges/', include('challenges.urls', namespace="challenges")),
    url(r'^teams/', include('teams.urls', namespace="teams")),
    url(r'^app_user/', include('app_user.urls', namespace="app_user")),
     url(r'^share/', include('share.urls', namespace="share")),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }))

share/urls.py
from django.conf.urls import patterns, url

from share import views

# routes to the correct view handler
urlpatterns = patterns('',
	url(r'^share_challenge/$', views.share_challenge, name='share_challenge'),
	url(r'^share_post/$', views.share_post, name='share_post'),
)

challenges/models.py
from django.db import models
from django.utils import timezone

from app_user.models import UserProfile


# Challenge Lookup Table
class Challenge(models.Model):
	challenge_title = models.CharField(max_length=64)
	challenge_description = models.TextField(max_length=1024)
	challenge_difficulty = models.IntegerField(default=5)
	challenge_time_in_days = models.IntegerField(default=7)
	challenge_ongoing = models.BooleanField(default=True)
	challenge_completion_user_failed = models.CharField(max_length=64)
	challenge_completion_user_tried = models.CharField(max_length=64)
	challenge_completion_user_did_good = models.CharField(max_length=64)
	challenge_completion_user_did_great = models.CharField(max_length=64)
	date_start = models.DateField()
	date_end = models.DateField()
	is_active = models.BooleanField(default=True)

	def __unicode__(self):
		return self.challenge_title


# User challenge list
class ChallengeList(models.Model):
	challenge = models.ForeignKey(Challenge)
	user = models.ForeignKey(UserProfile, null=True, blank=True)
	has_completed = models.BooleanField(default=False)
	level_of_complete = models.IntegerField(null=True, blank=True)
	start_date = models.DateTimeField('Challenge Start Date')
	achieved_date = models.DateTimeField(null=True, blank=True)

	def __unicode__(self):
		return self.user.user.username + " - " + self.challenge.challenge_title

challenges/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.utils import timezone
from django import forms
from dashboard.templatetags import dashboard_extras
import json

from app_user.models import UserProfile
from challenges.models import Challenge, ChallengeList
from points import points_controller
from app_user.AppUserController import get_header_string


# Chooser for the current challenge, uses an AJAX request
class ChallengeForm(forms.Form):
	challenge_id = forms.IntegerField()


# Survery after challenge has been completed
class ChallengeCompleteForm(forms.Form):
	challenge_status = forms.ChoiceField(widget=forms.RadioSelect(), required=True, label="")


# Main challenge page, shows different user challenge data
def challenge_index(request):
	profile = get_object_or_404(UserProfile, user=request.user)
	# get different lists
	user_challenge_list = ChallengeList.objects.filter(user=profile)
	completed_list = user_challenge_list.filter(user=profile, level_of_complete__isnull=False)
	challenge_list = Challenge.objects.exclude(id__in=[c.challenge.id for c in user_challenge_list])\
		.exclude(is_active=False)\
		.order_by('-challenge_difficulty')

	for unfiltered_challenged in challenge_list:
		if timezone.now().date() < unfiltered_challenged.date_start or timezone.now().date() > unfiltered_challenged.date_end:
			challenge_list = challenge_list.exclude(pk=unfiltered_challenged.pk)


	# remove ongoing challenges if they have been completed
	user_challenge_list = user_challenge_list.filter(level_of_complete__isnull=True)
	return render(request, 'challenges/index.html', {'title': ': Your Challenges', 'header_string': get_header_string(profile), 'user_challenge_list': user_challenge_list, 'challenge_list': challenge_list, 'completed_list': completed_list})


# for AJAX challenge update
def challenge_update(request):
	response_data = {
		'success': False
	}
	profile = UserProfile.objects.get(user=request.user)
	if profile:
		if request.method == 'POST':
			form = ChallengeForm(request.POST)
			if form.is_valid():
				challenge = Challenge.objects.get(pk=form.cleaned_data['challenge_id'])
				if challenge:
					cl = ChallengeList(challenge=challenge, user=profile, start_date=timezone.now())
					cl.save()
					response_data['success'] = True
	return HttpResponse(json.dumps(response_data), 'application/javascript')


# Final challenge complete page, sets challenges as complete
def challenge_complete(request):
	# Make sure the passed id hasn't been tampered with
	try:
		id = int(request.GET.get('challenge_id'))
	except ValueError:
		raise Http404("Malformed URL")

	# Get all user and challenge info and check it is correct
	profile = get_object_or_404(UserProfile, user=request.user)
	challenge = get_object_or_404(Challenge, id=id)
	user_challenge = get_object_or_404(ChallengeList, user=profile, challenge=challenge, level_of_complete__isnull=True)

	# Check that the correct challenge id is sent through to prevent cheating
	if dashboard_extras.get_days_left(user_challenge) <= 0:
		user_challenge.has_completed = True
		user_challenge.save()
	else:
		raise Http404("Malformed URL")

	# set options
	user_results = [(1, user_challenge.challenge.challenge_completion_user_failed),
					(2, user_challenge.challenge.challenge_completion_user_tried),
					(3, user_challenge.challenge.challenge_completion_user_did_good),
					(4, user_challenge.challenge.challenge_completion_user_did_great)]

	if request.method == 'POST':
		if not user_challenge.has_completed:
			raise Http404("Malformed URL")
		form = ChallengeCompleteForm(data=request.POST)
		form.fields['challenge_status'].choices = user_results
		if form.is_valid():
			user_challenge.level_of_complete = form.cleaned_data['challenge_status']
			user_challenge.save()
			points_controller.assign_points(profile, (int(user_challenge.level_of_complete) * int(user_challenge.challenge.challenge_difficulty)) * int(points_controller.get_multiplier()), "challenge", user_challenge.id)
			return HttpResponseRedirect(reverse('challenges:challenge_reward') + "?challenge_id=" + str(id) + "&reward=true")
	else:
		form = ChallengeCompleteForm()
		form.fields['challenge_status'].choices = user_results

	return render(request, 'challenges/complete.html', {'title': ': Complete', 'header_string': get_header_string(profile), 'user_challenge': user_challenge, 'form': form, 'id': id})


# Challenge reward page, shows amount of points the user has gained
def challenge_reward(request):
	# Make sure the passed id hasn't been tampered with
	try:
		id = int(request.GET.get('challenge_id'))
	except ValueError:
		raise Http404("Malformed URL")

	# Get all user and challenge info and check it is correct
	profile = get_object_or_404(UserProfile, user=request.user)
	challenge = get_object_or_404(Challenge, id=id)
	user_challenge = get_object_or_404(ChallengeList, user=profile, challenge=challenge, level_of_complete__isnull=False)
	score = points_controller.get_score_by_type("challenge", user_challenge.id)

	return render(request, 'challenges/reward.html', {'title': ': Reward', 'header_string': get_header_string(profile), 'user_challenge': user_challenge, 'score': score})

challenges/templates/challenges/complete.html
{% extends "base/base.html" %}

{% block content %}
	<section class="focus-section">
		<div class="card">
			<div class="card-title">Mission Complete: {{ user_challenge.challenge.challenge_title }}<br>How do you think you did?</div>
			<form action="{% url 'challenges:challenge_complete' %}?challenge_id={{id}}" method="post">
				{% csrf_token %}
				{{ form }}
				<li>
					<input type="submit" value="Submit" />
				</li>
			</form>
		</div>
	</section>
{% endblock %}

challenges/templates/challenges/index.html
{% extends "base/base.html" %}
{% load staticfiles %}
{% load dashboard_extras %}

{% block head %}
	<link rel="stylesheet" type="text/css" href="{% static 'challenges/css/challenges.css' %}">
{% endblock %}
{% block content %}
	<section class="focus-section">
		<div class="card">
			<ul>
				<div id="active-challenges">
					<div class="card-title">Your Active Challenges</div>
					{% if user_challenge_list %}
						{% for active_challenge in user_challenge_list %}
							<div onclick="show_challenge_info('Challenge: {{ active_challenge.challenge.challenge_title }}', [{'title': 'Description', 'content': '{{ active_challenge.challenge.challenge_description }}'}, {'title': 'Challenge Difficulty', 'content': '{{ active_challenge.challenge.challenge_difficulty }}/10'}])">
								<li>
									{% if active_challenge|get_days_left <= 0 %}
									<p>{{ active_challenge.challenge.challenge_title }} - Complete!</p>
									<div class="card-button inline-button right prevent-notification" value='{% url 'challenges:challenge_complete' %}?challenge_id={{ active_challenge.challenge.id }}'>Log progress</div>
									<br>
									<p>
										<span class="card-button inline-button space">INFO</span>
									</p>
									{% else %}
									<p>
										<span class="general-title">{{ active_challenge.challenge.challenge_title }}</span>
										<br>
										<span class="tagline-text">Days Left:&nbsp;<span class="challenge-time">{{ active_challenge|get_days_left }}</span></span>
										<br>
										<span class="card-button inline-button space">INFO&nbsp;</span>
										<span class="card-button inline-button space prevent-notification" value="{% url 'share:share_challenge' %}?challenge_id={{ active_challenge.challenge.id }}">&nbsp;Share</span>
									</p>
									<div class="progress-bar-outer">
										<div class="progress-bar-inner-wrapper">
											<div class="progress-bar-inner" style="width: {{ active_challenge|get_progress_percentage}}%"></div>
										</div>
									</div>
								</li>
							</div>
							{% endif %}
						{% endfor %}
					{% else %}
						<li>
							<div class="empty-text">This looks a bit empty, start a challenge or three so we can make Dorset a better place!</div>
						</li>
					{% endif %}
				</div>
			</ul>
		</div>
	</section>
	<section class="focus-section">
		<div class="card">
			<div class="card-title">Challenge List</div>
			<ul>
				{% for challenge in challenge_list %}
					<div onclick="show_challenge_info('Challenge: {{ challenge.challenge_title }}', [{'title': 'Description', 'content': '{{ challenge.challenge_description }}'}, {'title': 'Challenge Difficulty', 'content': '{{ challenge.challenge_difficulty }}/10'}])">
						<li>
							<p>
								<span class="general-title">{{ challenge.challenge_title }}</span>
								<br>
								<span class="tagline-text">Days To Complete:&nbsp;<span class="challenge-time">{{ challenge.challenge_time_in_days }}</span></span>
								<br>
								<span class="card-button inline-button space">INFO</span>
							</p>
							<div class="check-box" value="{{challenge.id}}"/>
						</li>
					</div>
				{% endfor %}
			</ul>
		</div>
	</section>
	<section class="focus-section">
		<div class="card">
			<div class="card-title">Completed List</div>
			<ul>
				{% for complete_challenge in completed_list %}
					<li>
						<p>{{ complete_challenge.challenge.challenge_title }}</p>
						<div class="card-button inline-button right" onclick='buttonClick("{% url 'challenges:challenge_reward' %}?challenge_id={{ complete_challenge.challenge.id }}")'>View</div>
						<br>
					</li>
				{% endfor %}
			</ul>
		</div>
	</section>
	<script>
		function init()
		{
			var objCheckBoxes = document.getElementsByClassName('check-box');
			for(var i = 0;i < objCheckBoxes.length; i++)
			{
				$(objCheckBoxes[i]).click(checkbox_press);
			}
			var objFinishedButtons = document.getElementsByClassName('prevent-notification');
			for(var i = 0;i < objFinishedButtons.length; i++)
			{
				$(objFinishedButtons[i]).click(function(e){
					e.stopPropagation();
					buttonClick(e.target.getAttribute("value"));
				});
			}
		}

		function buttonClick(url)
        {
            window.location.href = url;
        }

		function show_challenge_info(title, arrData)
		{
			var container = document.createElement('span');

			build_summary_data(container, arrData);

			show_notification(title, [container]);
		}

		function build_summary_data(container, arrData)
		{
			for(var i = 0; i < arrData.length; i++)
			{
				var attribute_title = document.createElement('p');
				attribute_title.textContent = arrData[i].title;
				attribute_title.className = "general-title";

				attribute_title.appendChild(document.createElement('br'));

				var attribute_content = document.createElement('span');
				attribute_content.innerHTML = arrData[i].content;
				attribute_content.className = "tagline-text";
				attribute_title.appendChild(attribute_content);

				container.appendChild(attribute_title);
				if(i < arrData.length - 1)
				{
					container.appendChild(document.createElement('br'));
					container.appendChild(document.createElement('br'));
				}
			}
		}

		function checkbox_press(e)
		{
			e.stopPropagation();
			e.target.parentNode.setAttribute("class", "processing");
			e.target.setAttribute("class", "check-box-checked");
			$.post("{% url 'challenges:challenge_update' %}",
			{
				challenge_id: e.target.getAttribute("value")
			},
			function(data){
				if(data.success)
				{
					var objActiveChallenges = document.getElementById("active-challenges");
					//checks if no challenges are set yet
					var objEmptyText = objActiveChallenges.getElementsByClassName("empty-text");
					if(objEmptyText.length > 0)
					{
						objEmptyText[0].parentNode.parentNode.removeChild(objEmptyText[0].parentNode);
					}
					//list item container
					var objListItemContainer = document.createElement('div');
					objListItemContainer.setAttribute("onclick", e.target.parentNode.parentNode.getAttribute("onclick"));

					//creating main node
					var objNewActiveChallenge = document.createElement('li');

					//get local challenge info
					var title = e.target.parentNode.getElementsByClassName("general-title")[0].textContent;
					var time = e.target.parentNode.getElementsByClassName("challenge-time")[0].textContent;
					var id = e.target.parentNode.getElementsByClassName("check-box-checked")[0].getAttribute("value");

					//creating title node
					var objNewActiveChallengeTitle = document.createElement('p');
					var objNewActiveChallengeTitleText = document.createTextNode(title);
					objNewActiveChallengeTitle.appendChild(objNewActiveChallengeTitleText);

					objNewActiveChallengeTitle.appendChild(document.createElement('br'));

					//creating days left span
					var objNewActiveChallengeDays = document.createElement('span');
					var objNewActiveChallengeDaysText = document.createTextNode("Days Left: " + time);
					objNewActiveChallengeDays.setAttribute("class", "tagline-text");
					objNewActiveChallengeDays.appendChild(objNewActiveChallengeDaysText);
					objNewActiveChallengeTitle.appendChild(objNewActiveChallengeDays);

					objNewActiveChallengeTitle.appendChild(document.createElement('br'));

					var objNewActiveChallengeInfo = document.createElement('span');
					objNewActiveChallengeInfo.innerHTML = "INFO&nbsp;";
					objNewActiveChallengeInfo.className = "card-button inline-button space";
					objNewActiveChallengeTitle.appendChild(objNewActiveChallengeInfo);

					var objNewActiveChallengeShare = document.createElement('span');
					objNewActiveChallengeShare.innerHTML = "&nbsp;SHARE";
					objNewActiveChallengeShare.className = "card-button inline-button space prevent-notification";
					objNewActiveChallengeShare.setAttribute("value", "{% url 'share:share_challenge' %}?challenge_id=" + id);
					objNewActiveChallengeTitle.appendChild(objNewActiveChallengeShare);

					$(objNewActiveChallengeShare).click(function(e){
						e.stopPropagation();
						buttonClick(e.target.getAttribute("value"));
					});

					objNewActiveChallenge.appendChild(objNewActiveChallengeTitle);

					//progress bar
					var objNewActiveChallengeProgressOuter = document.createElement('div');
					var objNewActiveChallengeProgressInnerWrapper = document.createElement('div');
					var objNewActiveChallengeProgressInner = document.createElement('div');

					objNewActiveChallengeProgressOuter.setAttribute("class", "progress-bar-outer");
					objNewActiveChallengeProgressInnerWrapper.setAttribute("class", "progress-bar-inner-wrapper");
					objNewActiveChallengeProgressInner.setAttribute("class", "progress-bar-inner");
					objNewActiveChallengeProgressInner.setAttribute("style", "width: 0.1%");

					objNewActiveChallengeProgressInnerWrapper.appendChild(objNewActiveChallengeProgressInner);
					objNewActiveChallengeProgressOuter.appendChild(objNewActiveChallengeProgressInnerWrapper);
					objNewActiveChallenge.appendChild(objNewActiveChallengeProgressOuter);

					//finally adding to the main challenge node
					objListItemContainer.appendChild(objNewActiveChallenge);
					objActiveChallenges.appendChild(objListItemContainer);

					e.target.parentNode.parentNode.removeChild(e.target.parentNode);
				}
				else
				{
					e.target.parentNode.setAttribute("class", "");
					e.target.setAttribute("class", "check-box");
				}
			}, "json");
		}
		{% include "base/token.js" %}
	</script>
{% endblock %}

challenges/templates/challenges/reward.html
{% extends "base/base.html" %}
{% load staticfiles %}

{% block head %}
	<link rel="stylesheet" type="text/css" href="{% static 'challenges/css/challenges.css' %}">
{% endblock %}

{% block content %}
	<section class="focus-section">
		<div class="card">
			<div class="card-title">Mission Complete: {{ user_challenge.challenge.challenge_title }}</div>
			<ul>
				<li>
					<div class="reward-title">Well Done!</div>
					<div class="reward-score">Score: <span id="show-score">0</span></div>
				</li>
				<li>
					<div class="card-inline-title">Summary</div>
					<br>
					<div>Mission</div>
					<div class="tagline-text">{{ user_challenge.challenge.challenge_title }}</div>
					<br>
					<div>Description</div>
					<div class="tagline-text">{{ user_challenge.challenge.challenge_description|safe }}</div>
					<br>
					<div>Difficulty</div>
					<div class="tagline-text">{{ user_challenge.challenge.challenge_difficulty }}/10</div>
				</li>
				<li>
					<div class="card-button" onclick='buttonClick("{% url 'challenges:index' %}")'>Back to challenges</div>
				</li>
			</ul>
		</div>
	</section>

	<script>
		var intScore = {{ score }};
		var intShowScore = 0;
		var domScoreSpan = document.getElementById("show-score");
		var arrScoreAppliers = [{applyScore:1, limit:10}, {applyScore:10, limit:100}, {applyScore:100, limit:1000}];
		var intCurrentApplier = 0;
		var hasEnded = false;
		var now,
			dt   = 0,
			last = timestamp(),
			step = 1/30;

		function update()
		{
			intShowScore += arrScoreAppliers[intCurrentApplier].applyScore;
			if(intShowScore >= arrScoreAppliers[intCurrentApplier].limit)
			{
				if(intCurrentApplier < arrScoreAppliers.length - 1)
				{
					intCurrentApplier++;
				}
			}
			if(intShowScore > intScore)
			{
				intShowScore = intScore;
				//document.getElementById("navbar-header-string").innerHTML += "<span style='color: #FFFFFF'>+" + intScore + "</span>";
				end();
			}
		}

		function render()
		{
			domScoreSpan.innerText = intShowScore.toString();
		}

		function end()
		{
			hasEnded = true;
		}

		function frame() {
			now = timestamp();
			dt = dt + Math.min(1, (now - last) / 1000);
			while(dt > step) {
			dt = dt - step;
			update(step);
			}
			render(dt);
			last = now;
			if(hasEnded == false)
			{
				requestAnimationFrame(frame);
			}
		}

		function timestamp() {
		  return window.performance && window.performance.now ? window.performance.now() : new Date().getTime();
		}

		function init()
		{
			requestAnimationFrame(frame);
		}

		window.requestAnimFrame = (function(){
		  return  window.requestAnimationFrame       ||
				  window.webkitRequestAnimationFrame ||
				  window.mozRequestAnimationFrame    ||
				  function( callback ){
					window.setTimeout(callback, 1000 / 30);
				  };
		})();

		function buttonClick(url)
        {
            window.location.href = url;
        }
	</script>
{% endblock %}