clsd_app/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'clsd_app.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^', include('dashboard.urls', namespace="dashboard")),
    url(r'^dashboard/', include('dashboard.urls', namespace="dashboard")),
    url(r'^challenges/', include('challenges.urls', namespace="challenges")),
    url(r'^teams/', include('teams.urls', namespace="teams")),
    url(r'^app_user/', include('app_user.urls', namespace="app_user")),
     url(r'^share/', include('share.urls', namespace="share")),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }))

share/urls.py
from django.conf.urls import patterns, url

from share import views

# routes to the correct view handler
urlpatterns = patterns('',
	url(r'^share_challenge/$', views.share_challenge, name='share_challenge'),
	url(r'^share_post/$', views.share_post, name='share_post'),
)

teams/urls.py
from django.conf.urls import patterns, url

from teams import views

# routes to the correct view handler
urlpatterns = patterns('',
	url(r'^create/$', views.create_team_view, name='create_team'),
	url(r'^list/$', views.list_team_view, name='list_teams'),
	url(r'^team_detail/$', views.team_detail_view, name='team_detail'),
	url(r'^join/$', views.team_join_view, name='join_team'),
)

teams/models.py
from django.db import models
import os


def get_media_path(instance, filename):
	file_name, file_extension = os.path.splitext(filename)
	return os.path.join('teams/' + str(instance.pk) + '/img' + file_extension)


# Stores different teams
class Team(models.Model):
	team_name = models.CharField(max_length=128)
	score = models.IntegerField(default=0)
	image = models.ImageField(upload_to=get_media_path, null=True, blank=True)
	signup_date = models.DateTimeField('signup date')

	def __unicode__(self):
		return self.team_name

teams/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, Http404
from django.core.urlresolvers import reverse
from django import forms
from django.utils import timezone
from django.db import IntegrityError
from app_user.models import UserProfile
from django.core.files.images import get_image_dimensions

from teams.models import Team
from app_user.AppUserController import get_header_string


# Form for team creation, checks if uploaded image is too big
class TeamForm(forms.Form):
	team_name = forms.CharField(label='Team Name', max_length=100)
	image = forms.ImageField(label='Upload a team image (Limit 2MB)')

	def clean_image(self):
		picture = self.cleaned_data.get("image")
		if not picture:
			raise forms.ValidationError("There's something wrong with the image")
		else:
			w, h = get_image_dimensions(picture)
			if w > 256:
				raise forms.ValidationError("Width %i pixels wide. Please limit images to 256x256" % w)
			if h > 256:
				raise forms.ValidationError("Height %i pixels wide. Please limit images to 256x256" % h)
			if picture._size > 2*1024*1024:
					raise forms.ValidationError("The image should be less than 2MB")
		return picture


# Team creation handler
def create_team_view(request):
	profile = get_object_or_404(UserProfile, user=request.user)
	if profile.team is None:
		if request.method == 'POST':
			form = TeamForm(request.POST, request.FILES)
			if form.is_valid():
				try:
					t = Team(team_name=form.cleaned_data['team_name'], signup_date=timezone.now())
					t.score += profile.score
					t.save()

					profile.team = t
					profile.save()

					# saving the image after the team has been created
					t.image = form.cleaned_data['image']
					t.save()
					profile.save()
					return HttpResponseRedirect(reverse('dashboard:dash_home'))
				except IntegrityError:
					pass
		else:
			form = TeamForm()
	else:
		raise Http404

	return render(request, 'teams/create_team.html', {'title': ': Create Team', 'header_string': get_header_string(profile), 'form': form})


# Lists all teams by descending order
def list_team_view(request):
	profile = get_object_or_404(UserProfile, user=request.user)
	team_list = Team.objects.order_by('-score')
	return render(request, 'teams/teams.html', {'title': ': Team Leaderboard', 'header_string': get_header_string(profile), 'team_list': team_list})


# Returns full team details
def team_detail_view(request):
	# Make sure the passed id hasn't been tampered with
	try:
		id = int(request.GET.get('team_id'))
	except ValueError:
		raise Http404("Malformed URL")

	profile = get_object_or_404(UserProfile, user=request.user)
	team = get_object_or_404(Team, pk=id)
	team_profiles = UserProfile.objects.filter(team=team).order_by('-score')[:20]

	no_team = False
	if profile.team is None:
		no_team = True

	is_user_team = False
	if profile.team == team:
		is_user_team = True

	return render(request, 'teams/team_detail.html', {'title': ': Team ' + team.team_name, 'header_string': get_header_string(profile), 'team': team, 'team_profiles': team_profiles, 'no_team': no_team, 'team_id': id, 'is_user_team': is_user_team})


# Allows team to be joined
def team_join_view(request):
	# Make sure the passed id hasn't been tampered with
	try:
		id = int(request.GET.get('team_id'))
	except ValueError:
		raise Http404("Malformed URL")

	profile = get_object_or_404(UserProfile, user=request.user)
	team = get_object_or_404(Team, pk=id)

	if profile.team is None:
		profile.team = team
		profile.save()
		team.score += profile.score
		team.save()

	return HttpResponseRedirect(reverse('teams:team_detail') + '?team_id=' + str(id))

teams/templates/teams/create_team.html
{% extends "base/base.html" %}

{% block content %}
	<section class="focus-section">
		<div class="card">
			<div class="card-title">Create your own team</div>
			<form action="{% url 'teams:create_team' %}" method="post" enctype="multipart/form-data">
				{% csrf_token %}
				{{ form.as_ul }}
				<li>
					<input type="submit" value="Submit" />
				</li>
			</form>
		</div>
	</section>
{% endblock %}

teams/templates/teams/team_detail.html
{% extends "base/base.html" %}

{% block content %}
	<section class="focus-section">
		<ul>
			<div class="card">
				<div class="card-title">Team {{ team.team_name }}</div>
					<li>
						{% if no_team %}
							<p>{{ team.team_name }}
								<br>
								<span class="tagline-text">Score:&nbsp;{{ team.score }}</span>
							</p>
							<div class="list-icon">
								<img src="{{ MEDIA_URL }}{{ team.image }}" width="75" height="75">
							</div>
							<div class="card-button" style="display: block;" onclick='buttonClick("{% url 'teams:join_team' %}?team_id={{ team_id }}")'>Join</div>
						{% else %}
							<p style="height: 60px;">{{ team.team_name }}
								<br>
								<span class="tagline-text">Score:&nbsp;{{ team.score }}</span>
							</p>
							<div class="list-icon">
								<img src="{{ MEDIA_URL }}{{ team.image }}" width="75" height="75">
							</div>
							{% if is_user_team %}
							<p style="display: block;">You are a member</p>
							{% endif %}
						{% endif %}
					</li>
			</div>
			<div class="card">
				<div class="card-title">Team Members</div>
				{% for profile in team_profiles %}
				<li>
					<p>{{ profile.user.username }}
						<br>
						<span class="tagline-text">Score:&nbsp;{{ profile.score }}</span>
					</p>
				</li>
				{% endfor %}
			</div>
		</ul>
	</section>

	<script type="application/javascript">
		function buttonClick(url)
        {
            window.location.href = url;
        }
	</script>
{% endblock %}

teams/templates/teams/teams.html
{% extends "base/base.html" %}

{% block content %}
	<section class="focus-section">
		<ul>
			<div class="card">
			<div class="card-title">Team Leaderboard</div>
				{% for team in team_list %}
				<li>
					<p>{{ team.team_name }}
						<br>
						<span class="tagline-text">Score:&nbsp;{{ team.score }}</span>
					</p>
					<div class="list-icon">
						<img src="{{ MEDIA_URL }}{{ team.image }}" width="75" height="75">
					</div>
					<div class="card-button join" value="{% url 'teams:team_detail' %}?team_id={{ team.id }}" style="display: block">View</div>
				</li>
				{% endfor %}
			</div>
		</ul>
	</section>

	<script>
		function init()
		{
			var objFinishedButtons = document.getElementsByClassName('card-button join');
			for(var i = 0;i < objFinishedButtons.length; i++)
			{
				$(objFinishedButtons[i]).click(function(e){
					e.stopPropagation();
					buttonClick(e.target.getAttribute("value"));
				});
			}
		}

        function buttonClick(url)
        {
            window.location.href = url;
        }
	</script>
{% endblock %}