app_user/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

from app_user import views

# routes to the correct view handler
urlpatterns = patterns('',
	url(r'^create/$', views.create_user_view, name='create_user'),
	url(r'^login/$', views.login_view, name='log_in'),
	url(r'^logout/$', views.logout_view, name='log_out'),
)

challenges/urls.py
from django.conf.urls import patterns, url

from challenges import views

# routes to the correct view handler
urlpatterns = patterns('',
	url(r'^$', views.challenge_index, name='index'),
	url(r'^challenge_update/$', views.challenge_update, name='challenge_update'),
	url(r'^challenge_complete/$', views.challenge_complete, name='challenge_complete'),
	url(r'^challenge_reward/$', views.challenge_reward, name='challenge_reward'),

)

clsd_app/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'clsd_app.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^', include('dashboard.urls', namespace="dashboard")),
    url(r'^dashboard/', include('dashboard.urls', namespace="dashboard")),
    url(r'^challenges/', include('challenges.urls', namespace="challenges")),
    url(r'^teams/', include('teams.urls', namespace="teams")),
    url(r'^app_user/', include('app_user.urls', namespace="app_user")),
     url(r'^share/', include('share.urls', namespace="share")),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }))

dashboard/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

from dashboard import views

# routes to the correct view handler
urlpatterns = patterns('',
	url(r'^$', views.dashboard, name='dash_home'),
	url(r'^about/', views.about, name='about'),
)

share/urls.py
from django.conf.urls import patterns, url

from share import views

# routes to the correct view handler
urlpatterns = patterns('',
	url(r'^share_challenge/$', views.share_challenge, name='share_challenge'),
	url(r'^share_post/$', views.share_post, name='share_post'),
)

teams/urls.py
from django.conf.urls import patterns, url

from teams import views

# routes to the correct view handler
urlpatterns = patterns('',
	url(r'^create/$', views.create_team_view, name='create_team'),
	url(r'^list/$', views.list_team_view, name='list_teams'),
	url(r'^team_detail/$', views.team_detail_view, name='team_detail'),
	url(r'^join/$', views.team_join_view, name='join_team'),
)

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import get_object_or_404, render

from app_user.models import UserProfile
from challenges.models import ChallengeList
from teams.models import Team
from app_user.AppUserController import get_dashboard_header_string

# Point of entry, decides which screen should be shown. Dashboard or home splash screen
def dashboard(request):
	if request.user.is_authenticated():
		return setup_dash(request)
	else:
		return setup_splash(request)


# gets user data needed for the dashboard
def setup_dash(request):
	profile = get_object_or_404(UserProfile, user=request.user)
	challenge_list = ChallengeList.objects.filter(user=profile, level_of_complete__isnull=True)
	team_list = Team.objects.order_by('-score')[:3]
	user_team = profile.team
	return render(request, 'dashboard/dashboard.html', {'title': ': Dashboard', 'header_string': get_dashboard_header_string(profile), 'profile': profile, 'user_challenge_list': challenge_list, 'team_list': team_list, 'user_team': user_team})


def setup_splash(request):
	return render(request, 'dashboard/splash.html')

def about(request):
	return render(request, 'dashboard/about.html')

dashboard/templates/dashboard/about.html
{% extends "base/base.html" %}
{% load staticfiles %}
{% load dashboard_extras %}

{% block head %}
{% endblock %}
{% block content %}
	<section class="focus-section">
		<ul>
			<div class="card">
			<div class="card-title">About</div>
				<br>
				<p>Communities Living Sustainably in Dorset (CLS) aims to support and enable people living in West Dorset to adapt to climate change and live more sustainable lifestyles.</p>
				<br>
				<p>This app has been made as a Bournemouth University student project to support people's change towards sustainable living and encourage it through the use of gamification.</p>
				<p></p>
			</div>
		</ul>
{% endblock %}

dashboard/templates/dashboard/dashboard.html
{% extends "base/base.html" %}
{% load staticfiles %}
{% load dashboard_extras %}

{% block head %}
	<link rel="stylesheet" type="text/css" href="{% static 'dashboard/css/dashboard.css' %}">
{% endblock %}
{% block content %}
	<section class="focus-section">
		<ul>
			<div class="card">
			<div class="card-title">Current Challenges</div>
			{% if user_challenge_list %}
				{% for active_challenge in user_challenge_list %}
					<div onclick="show_challenge_info('Challenge: {{ active_challenge.challenge.challenge_title }}', [{'title': 'Description', 'content': '{{ active_challenge.challenge.challenge_description }}'}, {'title': 'Challenge Difficulty', 'content': '{{ active_challenge.challenge.challenge_difficulty }}/10'}])">
						<li>
							{% if active_challenge|get_days_left <= 0 %}
							<p>{{ active_challenge.challenge.challenge_title }}</p>
							<div class="card-button inline-button right prevent-notification" value='{% url 'challenges:challenge_complete' %}?challenge_id={{ active_challenge.challenge.id }}'>Log progress</div>
							{% else %}
							<p>{{ active_challenge.challenge.challenge_title }}
								<br>
								<span class="tagline-text">Days Left:&nbsp;{{ active_challenge|get_days_left }}</span>
								<br>
								<span class="card-button inline-button space">INFO&nbsp;</span>
								<span class="card-button inline-button space prevent-notification" value="{% url 'share:share_challenge' %}?challenge_id={{ active_challenge.challenge.id }}">&nbsp;Share</span>
							</p>
							<div class="progress-bar-outer">
								<div class="progress-bar-inner-wrapper">
									<div class="progress-bar-inner" style="width: {{ active_challenge|get_progress_percentage}}%"></div>
								</div>
							</div>
							{% endif %}
						</li>
					</div>
				{% endfor %}
				<li>
					<div class="card-button" onclick='buttonClick("{% url 'challenges:index' %}")'>Manage Your Challenges</div>
				</li>
			{% else %}
				<li>
					<p>Your challenge progress is shown here, go set some ;-)</p>
				</li>
				<li>
					<div class="card-button" onclick='buttonClick("{% url 'challenges:index' %}")'>Set A Challenge</div>
				</li>
			{% endif %}
			</div>
		</ul>
	</section>

	<section class="focus-section">
		<ul>
			{% if user_team %}
			<div class="card">
				<div class="card-title">Team {{ user_team.team_name }}</div>
				<li>
					<p style="height: 75px;">{{ user_team.team_name }}
						<br>
						<span class="tagline-text">Score:&nbsp;{{ user_team.score }}</span>
					</p>
					<div class="list-icon">
						<img src="{{ MEDIA_URL }}{{ user_team.image }}" width="75" height="75">
					</div>
				</li>
			</div>
			{% endif %}
			<div class="card">
				<div class="card-title">Team Leaderboard</div>
			{% for team in team_list %}
				<li>
					<p style="height: 75px;">{{ team.team_name }}
						<br>
						<span class="tagline-text">Score:&nbsp;{{ team.score }}</span>
					</p>
					<div class="list-icon">
						<img src="{{ MEDIA_URL }}{{ team.image }}" width="75" height="75">
					</div>
				</li>
			{% endfor %}
			{% if user_team %}
				<li>
					<p>
						<div class="card-button" onclick='buttonClick("{% url 'teams:list_teams' %}")'>Team Leaderboards</div>
					</p>
				</li>
			{% else %}
				<li>
					<p>
						<div class="card-button" onclick='buttonClick("{% url 'teams:create_team' %}")'>Create a team</div>
						<div class="card-button" onclick='buttonClick("{% url 'teams:list_teams' %}")'>Join a team</div>
					</p>
				</li>
			{% endif %}
			</div>
		</ul>
	</section>

	<script>
		function init()
		{
			var objFinishedButtons = document.getElementsByClassName('prevent-notification');
			for(var i = 0;i < objFinishedButtons.length; i++)
			{
				$(objFinishedButtons[i]).click(function(e){
					e.stopPropagation();
					buttonClick(e.target.getAttribute("value"));
				});
			}
		}

        function buttonClick(url)
        {
            window.location.href = url;
        }

		function show_challenge_info(title, arrData)
		{
			var container = document.createElement('span');

			build_summary_data(container, arrData);

			show_notification(title, [container]);
		}

		function build_summary_data(container, arrData)
		{
			for(var i = 0; i < arrData.length; i++)
			{
				var attribute_title = document.createElement('p');
				attribute_title.textContent = arrData[i].title;
				attribute_title.className = "general-title";

				attribute_title.appendChild(document.createElement('br'));

				var attribute_content = document.createElement('span');
				attribute_content.innerHTML = arrData[i].content;
				attribute_content.className = "tagline-text";
				attribute_title.appendChild(attribute_content);

				container.appendChild(attribute_title);
				if(i < arrData.length - 1)
				{
					container.appendChild(document.createElement('br'));
					container.appendChild(document.createElement('br'));
				}
			}
		}
    </script>
{% endblock %}

dashboard/templates/dashboard/splash.html
{% extends "base/base_login.html" %}
{% load staticfiles %}

{% block content %}
    <section class="focus-section">
        <div class="card">
            <div class="card-image">
                <img src="{% static 'dashboard/img/bournemouth_beach.jpg' %}">
                <div class="card-title">Welcome to the CLS Dorset Web App</div>
            </div>
            <ul>
                <li>
                    <p style="max-width: inherit;">
						<a href="http://www.clsdorset.org.uk/" target="_blank">Communities Living Sustainably in Dorset (CLS)</a> aims to support and enable people living in West Dorset to adapt to climate change and live more sustainable lifestyles.
                        This app has been made as a Bournemouth University student project to support people's change towards sustainable living and encourage it through the use of gamification.
                    </p>
                </li>
                <li>
                    <div class="card-button" onclick='buttonClick("{% url 'app_user:log_in' %}")'>Log in</div>
                    <div class="card-button" onclick='buttonClick("{% url 'app_user:create_user' %}")'>Create Account</div>
                </li>
            </ul>
        </div>
		<div style="text-align: center; padding: 5px;"><a href="http://www.clsdorset.org.uk/" target="_blank"><img src="{% static 'dashboard/img/cls.png' %}"></a></div>
    </section>
    <script>
        function buttonClick(url)
        {
            window.location.href = url;
        }
    </script>
{% endblock %}