app_user/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

from app_user import views

# routes to the correct view handler
urlpatterns = patterns('',
	url(r'^create/$', views.create_user_view, name='create_user'),
	url(r'^login/$', views.login_view, name='log_in'),
	url(r'^logout/$', views.logout_view, name='log_out'),
)

challenges/urls.py
from django.conf.urls import patterns, url

from challenges import views

# routes to the correct view handler
urlpatterns = patterns('',
	url(r'^$', views.challenge_index, name='index'),
	url(r'^challenge_update/$', views.challenge_update, name='challenge_update'),
	url(r'^challenge_complete/$', views.challenge_complete, name='challenge_complete'),
	url(r'^challenge_reward/$', views.challenge_reward, name='challenge_reward'),

)

clsd_app/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'clsd_app.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^', include('dashboard.urls', namespace="dashboard")),
    url(r'^dashboard/', include('dashboard.urls', namespace="dashboard")),
    url(r'^challenges/', include('challenges.urls', namespace="challenges")),
    url(r'^teams/', include('teams.urls', namespace="teams")),
    url(r'^app_user/', include('app_user.urls', namespace="app_user")),
     url(r'^share/', include('share.urls', namespace="share")),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }))

dashboard/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

from dashboard import views

# routes to the correct view handler
urlpatterns = patterns('',
	url(r'^$', views.dashboard, name='dash_home'),
	url(r'^about/', views.about, name='about'),
)

share/urls.py
from django.conf.urls import patterns, url

from share import views

# routes to the correct view handler
urlpatterns = patterns('',
	url(r'^share_challenge/$', views.share_challenge, name='share_challenge'),
	url(r'^share_post/$', views.share_post, name='share_post'),
)

teams/urls.py
from django.conf.urls import patterns, url

from teams import views

# routes to the correct view handler
urlpatterns = patterns('',
	url(r'^create/$', views.create_team_view, name='create_team'),
	url(r'^list/$', views.list_team_view, name='list_teams'),
	url(r'^team_detail/$', views.team_detail_view, name='team_detail'),
	url(r'^join/$', views.team_join_view, name='join_team'),
)

clsd_app/templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head lang="en">
		<meta charset="UTF-8">
		<title>CLS Dorset{{ title }}</title>
		<meta name="description" content="Communities Living Sustainably in Dorset">
		<meta name="author" content="CLS Dorset">
		<link rel="stylesheet" type="text/css" href="{% static 'base/css/base.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'base/css/navbar.css' %}">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimal-ui=1">
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js" ></script>
		<script src="{% static 'base/js/BrowserTools.js' %}" type="text/javascript"></script>
		<script src="{% static 'base/js/NavbarController.js' %}" type="text/javascript"></script>
		{% block head %}{% endblock %}
	</head>
	<body>
		{% include "base/navbar.html" %}
		<div id="content">
			{% block content %}{% endblock %}
		</div>
		<script>
			var navbarController = null;

			$( document ).ready(function() {
				main_init();
			});

			function main_init()
			{
				navbarController = new NavbarController();
				//run the init method of subclassing templates if it exists
				if(typeof init != "undefined")
				{
					init();
				}
				BrowserTools.getInstance().onWindowResize();
			}

			function show_notification(title, arrContent)
			{
				document.getElementById("notification-title").textContent = title;
				var notification = document.getElementById("notification-bg");
				var content = document.getElementById("notification-content");

				//create exit button
				var objExitButton = document.createElement('div');
				objExitButton.setAttribute("class", "card-button");
				objExitButton.setAttribute("onclick", "remove_notification()");
				objExitButton.textContent = "ok";
				arrContent.push(objExitButton);

				//add new nodes to card
				for(var i = 0; i < arrContent.length; i++)
				{
					var objNewItem = document.createElement('li');
					objNewItem.appendChild(arrContent[i]);
					content.appendChild(objNewItem);
				}

				notification.setAttribute("style", "display: block;");
			}

			function remove_notification()
			{
				var notification = document.getElementById("notification-bg");
				var content = document.getElementById("notification-content");
				notification.setAttribute("style", "");

				//clear up old notification
				for(var i = 0; i < content.childNodes.length; i++)
				{
					content.removeChild(content.childNodes[i]);
					i--;
				}
			}
		</script>
		<div id="notification-bg">
			<div class="card notification">
				<div id="notification-title" class="card-title"></div>
				<ul id="notification-content"></ul>
			</div>
		</div>
	</body>
</html>

clsd_app/templates/base/base_login.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head lang="en">
		<meta charset="UTF-8">
		<title>CLS Dorset{{ title }}</title>
		<meta name="description" content="Communities Living Sustainably in Dorset">
		<meta name="author" content="CLS Dorset">
		<link rel="stylesheet" type="text/css" href="{% static 'base/css/base.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'base/css/navbar.css' %}">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimal-ui=1">
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js" ></script>
		<script src="{% static 'base/js/BrowserTools.js' %}" type="text/javascript"></script>
		{% block head %}{% endblock %}
	</head>
	<body onload="main_init()">
		{% include "base/navbar_login.html" %}
		<div id="content">
			{% block content %}{% endblock %}
		</div>
		<script>
			function main_init()
			{
				//run the init method of subclassing templates if it exists
				if(typeof init != "undefined")
				{
					init();
				}
				BrowserTools.getInstance().onWindowResize();
			}

			function show_notification(title, arrContent)
			{
				document.getElementById("notification-title").textContent = title;
				var notification = document.getElementById("notification-bg");
				var content = document.getElementById("notification-content");

				//create exit button
				var objExitButton = document.createElement('div');
				objExitButton.setAttribute("class", "card-button");
				objExitButton.setAttribute("onclick", "remove_notification()");
				objExitButton.textContent = "ok";
				arrContent.push(objExitButton);

				//add new nodes to card
				for(var i = 0; i < arrContent.length; i++)
				{
					var objNewItem = document.createElement('li');
					objNewItem.appendChild(arrContent[i]);
					content.appendChild(objNewItem);
				}

				notification.setAttribute("style", "display: block;");
			}

			function remove_notification()
			{
				var notification = document.getElementById("notification-bg");
				var content = document.getElementById("notification-content");
				notification.setAttribute("style", "");

				//clear up old notification
				for(var i = 0; i < content.childNodes.length; i++)
				{
					content.removeChild(content.childNodes[i]);
					i--;
				}
			}
		</script>
		<div id="notification-bg">
			<div class="card notification">
				<div id="notification-title" class="card-title"></div>
				<ul id="notification-content"></ul>
			</div>
		</div>
	</body>
</html>

clsd_app/templates/base/navbar.html
{% load staticfiles %}
<div id="navbar">
	<div id="navbar-content">
		<a href="{% url 'dashboard:dash_home' %}"><div class="navbar-title">CLS Dorset Web App<div id="navbar-header-string">{{ header_string }}</div></div></a>
		<img class="navbar-item-menu-mobile" src="{% static 'base/img/navbar/menu.png' %}">
		<div class="navbar-item-menu-mobile">Menu</div>
		<a href="{% url 'dashboard:dash_home' %}"><div class="navbar-item first">Home</div></a>
		<a href="{% url 'dashboard:about' %}"><div class="navbar-item">About</div></a>
		<a href="{% url 'challenges:index' %}"><div class="navbar-item">Challenges</div></a>
		<a href="{% url 'teams:list_teams' %}"><div class="navbar-item">Teams</div></a>
		<a href="{% url 'app_user:log_out' %}"><div class="navbar-item">Log Out</div></a>
	</div>
</div>
<li id="mobile-menu-list">
	<ul id="mobile-menu-unordered-list">
		<li><a href="{% url 'dashboard:dash_home' %}"><div class="navbar-item-mobile">Home</div></a></li>
		<li><a href="{% url 'dashboard:about' %}"><div class="navbar-item-mobile">About</div></a></li>
		<li><a href="{% url 'challenges:index' %}"><div class="navbar-item-mobile">Challenges</div></a></li>
		<li><a href="{% url 'teams:list_teams' %}"><div class="navbar-item-mobile">Teams</div></a></li>
		<li><a href="{% url 'app_user:log_out' %}"><div class="navbar-item-mobile">Log Out</div></a></li>
	</ul>
</li>

clsd_app/templates/base/navbar_login.html
{% load staticfiles %}
<div id="navbar">
	<div id="navbar-content">
		<a href="{% url 'dashboard:dash_home' %}"><div class="navbar-title">CLS Dorset Web App<div id="navbar-header-string">Not logged in</div></div></a>
	</div>
</div>